{{- if eq .Values.ingress.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if or (.Values.ingress.annotations) (.Values.ingress.clusterIssuer) }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
  {{- end }}
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "dotnet-chart.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
  {{- if eq .Values.ingress.tls.enabled true }}
  tls:
  - secretName: {{ .Values.ingress.tls.secretName }}
    hosts:
    {{- range .Values.ingress.tls.hosts }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}