apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotnet-chart.fullname" . }}
spec:
  selector:
    {{- include "dotnet-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}